export const SET_APP_CONFIG = 'SET_APP_CONFIG';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_USER = 'SET_USER';
export const SET_USER_CREATED_AT = 'SET_USER_CREATED_AT';
export const SET_CREDIT_CARDS = 'SET_CREDIT_CARDS';
export const SET_IS_USER_AUTH = 'SET_IS_USER_AUTH';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_MODAL = 'SET_MODAL';
export const SET_STATUS_BAR = 'SET_STATUS_BAR';
export const SET_ROUTE_HISTORY = 'SET_ROUTE_HISTORY';
export const SET_PLAN = 'SET_PLAN';
export const SET_FUTURE_DATA = 'SET_FUTURE_DATA';
export const SET_TOTAL_DEBT = 'SET_TOTAL_DEBT';
export const SET_SIGN_UP_CAROUSEL_VISITED_SCREEN =
  'SET_SIGN_UP_CAROUSEL_VISITED_SCREEN';

export const RESET_STORE = 'RESET_STORE';
export const RESET_ACCOUNTS = 'RESET_ACCOUNTS';
export const RESET_CREDIT_CARDS = 'RESET_CREDIT_CARDS';
export const RESET_USER = 'RESET_USER';
export const RESET_IS_USER_AUTH = 'RESET_IS_USER_AUTH';
export const RESET_ROUTE_HISTORY = 'RESET_ROUTE_HISTORY';
export const RESET_PLAN = 'RESET_PLAN';
export const RESET_FUTURE_DATA = 'RESET_FUTURE_DATA';
export const RESET_TOTAL_DEBT = 'RESET_TOTAL_DEBT';
export const RESET_SIGN_UP_CAROUSEL_VISITED_SCREEN =
  'RESET_SIGN_UP_CAROUSEL_VISITED_SCREEN';
