export default {
  TERMS_CONDITIONS: 'TermsConditions',
  SECURITY: 'Security',
  SUCCESS: 'Success',
  HOME: 'Home',
  SIGN_UP: 'SignUp',
  SIGN_IN: 'SignIn',
  PRIVACY: 'PrivacyPolicy',
  ADD_CARDS_MODAL: 'addCardsModal',
  DASHBOARD: 'Dashboard',
  FORGOT: 'Forgot',
  RECOVER_PASSWD: 'RecoverPassword',
  CONFIRM: 'ConfirmPassword',
  CARD_BALANCES: 'Balances',
  CARDS_DETAIL: 'Balances',
  MENU_SETTINGS: 'Settings',
  LINKED_ACCOUNTS: 'Accounts',
  DISCLAIMER: 'BetaDisclaimer',
  PLAN_SETTINGS: 'PlanSettings',
  PLAN_APPROACH: 'PlanApproach',
  PLAN_APPROACH_READONLY: 'PlanApproachReadonly',
  PLAN_REVIEW: 'PlanReview',
  PLAN_REVIEW_READONLY: 'PlanReviewReadonly',
  ONBOARD_CONGRATS: 'OnBoardingCongrats',
  ONBOARD_ADD_CARDS: 'OnBoardingAddCreditCards',
  ONBOARD_ADD_ACCOUNTS: 'OnBoardingAddAccounts',
  ONBOARD_PLAN_SETTINGS: 'OnBoardingPlanSettings',
  ONBOARD_PLAN_APPROACH: 'OnBoardingPlanApproach',
  ONBOARD_REVIEW_PLAN: 'OnBoardingPlanReview',
  ONBOARD_PLAN_SUCCESS: 'OnboardingPlanSuccess',
  NOTIFICATIONS: 'Notifications',
  PLAN_SUCCESS: 'PlanSuccess',
  SAFE_CONNECT: 'SafeConnect',
  SIGN_UP_CAROUSEL: 'SignUpCarrousel',
  CAROUSEL_CARD: 'CarouselCard',
  CAROUSEL_SECURITY: 'CarouselSecurity',
  CAROUSEL_WALLET: 'CarouselWallet',
  CAROUSEL_SAVE: 'CarouselSave',
};
export type routesType = {
  TERMS_CONDITIONS: string;
  SECURITY: string;
  SUCCESS: string;
  HOME: string;
  SIGN_UP: string;
  SIGN_IN: string;
  PRIVACY: string;
  ADD_CARDS_MODAL: string;
  DASHBOARD: string;
  FORGOT: string;
  RECOVER_PASSWD: string;
  CONFIRM: string;
  CARD_BALANCES: string;
  CARDS_DETAIL: string;
  MENU_SETTINGS: string;
  LINKED_ACCOUNTS: string;
  DISCLAIMER: string;
  PLAN_SETTINGS: string;
  PLAN_APPROACH: string;
  PLAN_APPROACH_READONLY: string;
  PLAN_REVIEW: string;
  PLAN_REVIEW_READONLY: string;
  ONBOARD_CONGRATS: string;
  ONBOARD_ADD_CARDS: string;
  ONBOARD_ADD_ACCOUNTS: string;
  ONBOARD_PLAN_SETTINGS: string;
  ONBOARD_PLAN_APPROACH: string;
  ONBOARD_REVIEW_PLAN: string;
  NOTIFICATIONS: string;
  PLAN_SUCCESS: string;
  SAFE_CONNECT: string;
  SIGN_UP_CAROUSEL: string;
  CAROUSEL_CARD: string;
  CAROUSEL_SECURITY: string;
  CAROUSEL_WALLET: string;
  CAROUSEL_SAVE: string;
};
