
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'
project 'Smash',
'Dev.Debug' => :debug,
'Dev.Release' => :release,
'Qa.Debug' => :debug,
'Qa.Release' => :release,
'Debug' => :debug,
"Release" => :release

target 'Smash' do
  # Pods for Smash
  
  pod 'Plaid', '2.0.8'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'SmashTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(configurations: ['Debug','Dev.Debug','Qa.Debug'])
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end
