import SmashButtonStory from './SmashBtn/myStory';
import CenterViewStory from './CenterView/CenterViewStory';
import SmashWelcomeStory from './SmashWelcome/SmashWelcomeStory';
import SmashInputTextStory from './SmashInputText/SmashInputTextStory';
import TextsStory from './Texts/TextsStory';
import InfoLayoutStory from './InfoLayout/InfoLayoutStory';
import DashboardView from './DashboardView/DashboardView';
import PlaidBanksLinksView from './Plaid/PlaidBanksLinksView';
import SettingMenuView from './SettingMenuView/SettingMenuView';
import LinkedAccountsView from './LinkedAccountsView/LinkedAccountsView';
import SmashModal from './SmashModal/SmashModalStory';
import SmashActionButton from './SmashActionButton/SmashActionButton';
import CardListItem from './CardListItem/CardListItem';
import PlanSettingsView from './PlanSettingsView/PlanSettingsView';
import PlanApproachView from './PlanApproachView/PlanApproachView';
import PlanReviewView from './PlanReviewView/PlanReviewView';
import CustomErrorModal from './CustomErrorModal/CustomErrorModal';
import DashboardTabNavigator from './DashboardTabNavigator/DashboardTabNavigator';
import CardListData from './CardListData/CardListData';
import Congratulations from './CongratulationsView/Congratulations';
import Onboarding from './Onboarding/Onboarding';
import NotificationsView from './NotificationsView/NotificationsView';
import PlanSuccessView from './PlanSuccessView/PlanSuccessView';
import SmashAnimLoader from './SmashAnimLoader/SmashAnimLoader';
import AddCardsView from './AddCardsView/AddCardsView';
import SignUpCarrousel from './SignUpCarrousel/SignUpCarrousel';
import CardUsageChart from './CardUsageChart/CardUsageChart';

CardUsageChart();
SignUpCarrousel();
AddCardsView();
SmashAnimLoader();
PlanSuccessView();
NotificationsView();
Onboarding();
Congratulations();
CardListData();
DashboardTabNavigator();
CustomErrorModal();
PlanReviewView();
PlanApproachView();
PlanSettingsView();
CardListItem();
DashboardView();
SmashActionButton();
SmashModal();
LinkedAccountsView();
SettingMenuView();
PlaidBanksLinksView();
SmashButtonStory();
CenterViewStory();
SmashWelcomeStory();
SmashInputTextStory();
TextsStory();
InfoLayoutStory();
